

---


- hosts: all
  ignore_unreachable: true
  become: true
  tasks:
  - name: install apache2 and php
    package:
      name: 
        - "{{ apache_pack }}"
        - "{{ php_pack }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

